# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 5 # 作成するPRの最大数を5に設定
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "Asia/Tokyo"
    # ignore:
    #   - dependency-name: "@types/node"
    #     versions: [">=20.19.0"] # 20.19.0より新しいバージョンのアップデート通知は無視(現在使ってる20.18.1までは通知する)
    groups:
      react:
        applies-to: version-updates
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      next:
        applies-to: version-updates
        patterns:
          - "next"
          - "eslint-config-next"
          - "@next/eslint-plugin-next"
